// tslint:disable-next-line: variable-name
export let app_strings = {
    HOME_ROUTE: '/user',
    TWO_ZERO_ONE: '200',
    CRED_INCORRECT: 'Incorrect Credentials',
    NO_INTERNET_CONNECTION: 'No Internet Connection',
    ERROR_OCCURRED: 'An unexpected error occurred',
    IMAGE_REQUIRED: 'User image is required',
    INVALID_FORM: 'Invalid form submission',
    SUCCESS: 'Successfully done',
    DEF_IMAGE_URL: 'assets/images/def-person-m.jpg',
    UPDATED: 'Updated Successfully',
    PLEASE_UPLOAD_IMAGE: 'Please upload image atleast',
    pleaseUploadPurchaseOrder: 'Please Upload PurchaseOrder',
    pleaseUploadEstimateOrder: 'Please Upload Estimate order',
    FILE_SIZE: 20,
    FILENAME: 'report',
    XLS_EXTENSION: 'xls',
    CSV: 'csv',
    TWO_ZERO_ZERO: 200,
    EXCEED_WORD_LIMIT: 'Exceed word limit',
    MODELS: {
        /* const models = {
Users, Uploads, Options, Cart,
CartRelation, Enquiry, Card, Address,
Newsfeed, CMS, Onboarding, Products, Artisan
} */
        Faq: 'Faq', Aboutus: 'About us', 'Patch- message': 'Patch-message', Testimonial: 'Testimonial', Banner: 'Banner', USP: 'USP', Industries: 'Industries', artisan_group: 'artisan_group', product_group: 'product_group',
        purchaseOrder: 'po',invoice:'invoice',
        enquiries: 'enquiries',
        estimate: 'estimate',
        subAdminCategory:'subAdminCategory',
        users: 'users', uploads: 'uploads', options: 'options',
        support:'support',
        story: 'stories',
        awards:'awards',
        cart: 'cart',
        cartRelation: 'cart_relation', enquiry: 'enquiry', card: 'card',
        address: 'address',
        category: 'category',
        newsfeed: 'newsfeed', cms: 'cms', onboarding: 'onboarding',
        products: 'products', artisan: 'artisan',
        brand:'brand',
        type_of_store: 'type_of_store', aboutus_sample: 'aboutus_sample', customer_important_sample: 'customer_important_sample', catalogue: 'catalogue', career: 'carrer', Team: 'team', Blogs: 'blogs',
        returnPolicy: 'return', privacy: 'privacy'
    },
    ALPHABET_PATTERN: /^[A-Za-z ]+$/,
    URL_PATTERN: '(https?://)?([\\da-z.-]+)\\.([a-z.]{2,6})[/\\w .-]*/?',
    IMAGE_VALIDATION: 'Image is mandatory',
    errorMsg: {
        pleaseSelectOneArtisan: 'Please select atleast one artisan ',
        pleaseSelectOneProduct: 'Please select atleast one Product ',
        groupNameEXIST: 'Group Name already exist ',
    }
};
